# Project information
site_name: 'Tabix'
site_description: 'Tabix DB Gui'
site_author: 'Igor Strykhar'
site_url: 'https://tabix.io/doc'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/smi2/tabix.ui'
edit_uri: 'edit/master/manual/docs/'
# Copyright
copyright: 'Copyright &copy; 2017 Igor Strykhar '

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: 'img/logo.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Menlo'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/smi2/tabix.ui'
    - type: 'twitter'
      link: 'https://twitter.com/tabix.io'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

extra_css:
  - 'stylesheets/extra.css'
# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde